# Generated by Django 5.2.8 on 2025-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='icons/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
