# Generated by Django 5.2.8 on 2026-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_budget',
            field=models.FloatField(default=0),
        ),
    ]
