# Generated by Django 5.2.8 on 2025-12-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('icon', models.CharField(choices=[('🏦', 'Bank'), ('💳', 'Card'), ('💰', 'Cash'), ('🐖', 'Saving')], default='🐖', max_length=5)),
            ],
        ),
    ]
