# Generated by Django 5.2.8 on 2026-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_category_user_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
