# Generated by Django 5.2.8 on 2026-01-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFA500', max_length=7),
        ),
    ]
